/*
REAL ESTATE SALES ANALYTICS
Dataset: re_dataset.sql 
Tables: regions, agents, properties, clients, sales
This file aims to simulate key business questions of a real-estate agency. It is related to revenue, sales performance, property inventory
and client purchases.
*/

-- ===================
--  BUSINESS REVENUE  |
-- ===================

--  Total revenue generated by the agency
SELECT 
  -- Gets the total sum of all sales generated by the agency
  SUM(sale_amount) AS total_generated_revenue
FROM sales;

-- Regions which generate the most revenue
WITH region_revenue AS (
  SELECT 
    r.region_id 
    , r.region_name 
    , s.sale_amount
  FROM regions AS r
  INNER JOIN properties AS p
    ON r.region_id = p.region_id
  INNER JOIN sales AS s
    ON p.property_id = s.property_id
)

SELECT 
  region_id
  , region_name
  , SUM(sale_amount) AS total_generated_revenue
FROM region_revenue
GROUP BY
  region_id
  , region_name
ORDER BY total_generated_revenue DESC;


-- Monthly revenue trends
WITH monthly_revenue AS (
  SELECT
     date_trunc('month', sale_date) AS month_year
    , SUM(sale_amount) AS total_sales
  FROM sales
  GROUP BY month_year
)

SELECT
  -- Formats the date_trunc for the results
  to_char(month_year, 'FMMonth YYYY')
  , total_sales
  -- Uses the LAG function to solve for revenue growth. It 
  , total_sales - LAG(total_sales) OVER (ORDER BY month_year ASC) AS revenue_growth
FROM monthly_revenue;
 
--====================
--  AGENT PERFORMANCE |
-- =================== 

-- Which agents generate the most revenue
SELECT
  a.agent_name
  , SUM(s.sale_amount) AS total_revenue
FROM agents AS a
INNER JOIN sales AS s
  ON a.agent_id = s.agent_id
GROUP BY 
  a.agent_id
  , a.agent_name
ORDER BY total_revenue DESC;


-- Agent Ranking (By total sales)
WITH agent_ranking AS (
  SELECT
    a.agent_name
    , SUM(s.sale_amount) AS total_sales
    -- Ranks agents according to the total sales they bring into the agency
    , RANK() OVER (ORDER BY SUM(s.sale_amount) DESC) agent_rank
  FROM agents AS a
  INNER JOIN sales AS s
    ON a.agent_id = s.agent_id
  GROUP BY 
    a.agent_id
    , a.agent_name
)

SELECT agent_name, total_sales, agent_rank
FROM agent_ranking;

-- Which agents close the highest-value deals on average?

