/*
REAL ESTATE SALES ANALYTICS
Dataset: re_dataset.sql 
Tables: regions, agents, properties, clients, sales
This file aims to simulate key business questions of a real-estate agency. It is related to revenue, sales performance, property inventory
and client purchases.
*/

-- ===================
--  BUSINESS REVENUE  |
-- ===================

--  Total revenue generated by the agency
SELECT 
  -- Gets the total sum of all sales generated by the agency
  SUM(sale_amount) AS total_generated_revenue
FROM sales;

-- Regions which generate the most revenue
WITH region_revenue AS (
  SELECT r.region_name 
    , s.sale_amount
  FROM regions AS r
  INNER JOIN properties AS p
    ON r.region_id = p.region_id
  INNER JOIN sales AS s
    ON p.property_id = s.property_id
)

SELECT region_name
  , SUM(sale_amount) AS total_generated_revenue
FROM region_revenue
GROUP BY region_name
ORDER BY total_generated_revenue DESC;


-- Monthly revenue trends
WITH monthly_revenue AS (
  SELECT 
    -- Gets the month of sales_date 
    date_trunc('month', sale_date) AS month_year
    -- Gets the sum of all total sales to get the monthly revenue
    , SUM(sale_amount) AS total_sales
  FROM sales
  GROUP BY month_year
)

SELECT
  -- Formats the date_trunc for the results
  to_char(month_year, 'FMMonth YYYY') AS month
  , total_sales
  -- Uses the LAG function to subtract the current month from the previous month to get data for revenue growth. 
  , total_sales - LAG(total_sales) OVER (ORDER BY month_year ASC) AS revenue_growth
FROM monthly_revenue;

-- Running revenue
WITH running_monthly AS (
  SELECT 
    date_trunc('month', sale_date) AS month_yr
    , SUM(sale_amount) AS monthly_revenue
    FROM sales
    GROUP BY month_yr
)

SELECT
  to_char(month_yr, 'FMMonth YYYY') AS month
  , monthly_revenue
  -- Takes the SUM per month and accumulates it overtime to show total revenue growth 
  , SUM(monthly_revenue) OVER(ORDER BY month_yr) AS running_total
FROM running_monthly;
 
--====================
-- AGENT PERFORMANCE |
--==================== 

-- Which agents generate the most revenue
SELECT
  a.agent_id
  , a.agent_name
  -- Gets the total SUM of all sales to organize the agents by total revenue
  , SUM(s.sale_amount) AS total_revenue
FROM agents AS a
INNER JOIN sales AS s
  ON a.agent_id = s.agent_id
GROUP BY 
  a.agent_id
  , a.agent_name
ORDER BY total_revenue DESC;

-- Agent Ranking (By total sales)
WITH agent_ranking AS (
  SELECT
    a.agent_name
      -- Collects the total sales by getting the sum of all sale amounts
    , SUM(s.sale_amount) AS total_sales
    -- Ranks agents according to the total sales they bring into the agency
    , RANK() OVER (ORDER BY SUM(s.sale_amount) DESC) agent_rank
  FROM agents AS a
  INNER JOIN sales AS s
    ON a.agent_id = s.agent_id
  GROUP BY 
    a.agent_id
    , a.agent_name
)

SELECT agent_name, total_sales, agent_rank
FROM agent_ranking;

-- Which agents close the highest-value deals on average?
SELECT 
  a.agent_name
  -- Averages out all agent sales
  , AVG(s.sale_amount) AS average_agent_sales
FROM agents AS a
INNER JOIN sales AS s
  ON a.agent_id = s.agent_id
GROUP BY
  a.agent_id
  , a.agent_name
ORDER BY average_agent_sales DESC;

-- Agent performance vs regional average
WITH agent_totals AS (
  SELECT a.agent_name
  , SUM(s.sale_amount) AS total_sale 
  , r.region_name
  FROM regions  AS r
  INNER JOIN agents AS a
    ON r.region_id = a.region_id
  INNER JOIN sales AS s
    ON a.agent_id = s.agent_id
  GROUP BY a.agent_name, r.region_name
)

SELECT agent_name
       , total_sale
       , region_name
       , AVG(total_sale) OVER (PARTITION BY region_name) AS regional_average
FROM agent_totals
ORDER BY total_sale DESC;

-- Comissions earned per agent

WITH agent_commission AS (
  SELECT a.agent_name
         , SUM(s.sale_amount) AS sale_amount 
         , a.commission_rate
  FROM agents AS a
  INNER JOIN sales AS s
    ON a.agent_id = s.agent_id
  GROUP BY agent_name, commission_rate
)

SELECT agent_name
       , ((sale_amount * commission_rate) / 100)::numeric(12,2) AS commission_earnings
FROM agent_commission
ORDER BY commission_earnings DESC;

--======================
-- PROPERTY PERFORMANCE |
--======================

-- Property types that sell the highest prices on average
SELECT
  property_type
  -- Collects the average listing price for each property type
  , AVG(listing_price) AS average_listing_price
FROM properties
GROUP BY property_type
ORDER BY average_listing_price DESC;


-- Average time it takes for a property to sell
WITH average_sale_time AS (
  SELECT 
    p.property_id
    -- Subtracts the total dates between the sale_date and the listing_date
    -- This is done so we cann collect all days between listing and sale
    , (s.sale_date - p.listing_date) AS days_difference
  FROM properties AS p
  INNER JOIN sales AS s
    ON p.property_id = s.property_id
)

SELECT
  -- Rounds the average so we can get an accurate number of total days on how long it takes to make a sale 
  ROUND(AVG(days_difference)) AS days_to_sell
FROM average_sale_time;

-- How many properties are sold, unsold, or reserved?
SELECT COUNT(CASE WHEN property_status ='sold' THEN 1 ELSE NULL END) AS sold_properties 
       , COUNT(CASE WHEN property_status ='unsold' THEN 1 ELSE NULL END) AS unsold_properties
       , COUNT(CASE WHEN property_status ='reserved' THEN 1 ELSE NULL END) AS reserved_properties
FROM properties;


-- PROPERTY CONVERSION RATES

WITH property_conversion AS (
  SELECT r.region_name
  , COUNT(*) AS properties_per_region
  , COUNT(CASE WHEN property_status = 'sold' THEN 1 ELSE NULL END) AS properties_sold
  FROM regions AS r
  INNER JOIN properties AS p
    ON r.region_id = p.region_id
  GROUP BY region_name
)

SELECT region_name
         , CONCAT(((properties_sold * 100.0) / properties_per_region)::numeric(12,0), '%') AS properties_sold_percentage
FROM property_conversion
ORDER BY properties_sold DESC;

--=================
-- CLIENT INSIGHTS|
--=================
-- Which clients are responsible for the highest-value purchases?
WITH highest_client_purchases AS (
  SELECT
    c.client_id
    , c.client_name
    , s.sale_amount 
  FROM sales AS s
  INNER JOIN clients AS c
    ON s.client_id = c.client_id 
) 

SELECT client_name, SUM(sale_amount) AS client_purchases
FROM highest_client_purchases
GROUP BY client_name
ORDER BY client_purchases DESC;
